:PROPERTIES:
:ID:       68e5fb34-78ba-44da-aa32-13c455d271cd
:END:
#+title: Filosofi

* Hidup berfilosofi
Di kehidupan kita memang terkadang menantang, dan terkadang membuat kita stres dan banyak pikiran oleh karena itu saya memilih filosofi stoic sebagai pemandu hidup saya, agar lebih tenang.

* Prinsip prinsip Filosofi stoic
** Dikotomi kendali
Terkadang kita selalu memikirkan hal yang di luar kendali kita, contohnya
terjebak macet, terkena bencana alam, dan lain lain yang berhubungan dengan hal eksternal, oleh karena itu kita seharusnya mengendalikan apa yang bisa kita lakukan atau di sebut hal internal, fokus lah pada hal yang bisa kendalikan.

** Premedatatio Malorum
Prinsip ini menjelaskan kita seharusnya tidak boleh takut dengan, apapun yang membuat kita menderita, dan kita seharusnya menerimanya penderitaan itu yang akan datang, agar kita siap menerima penderitaan itu.

** Amor fati
Prinsip menekankan kita untuk menerima nasip kita, jadi konsepnya kita harus menerima diri apadanya.

[[id:2a89232c-54d6-4b7a-a84e-1ab1570031cd][Self Development]]
